### ISSUE TITLE
Consider using auth.User as one-to-one for Signup

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#15]
In Django is built-in model auth.User which has properties first_name, last_name, email, password and others. We could use it as one-to-one to Signup and omit duplicate fields there.
The main benefit of using this is, that we could use standart Django authentification backends.

**Comment by just-paja** [comment]
We can extend it, but shouldn't use it. (Admin) User and Festival Participant are really two different things. We will also need (later) user model to authenticate against LDAP so that Improliga officials are given access to the administration without having a need to have special user account for this service.
