### ISSUE TITLE
Signup.team should be made by ForegnKey

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#19]
`Signup.team` should be made by `ForegnKey` if we want to use it for things like listing signups from one team or gym assignment.

**Comment by just-paja** [comment]
It can be done from the database perspective, but I am not sure about inputting the team field in UI. We cannot give users a list of choices because we don't know all the possible improv groups our participants may be from.

Consider this: I am a participant whose origin is from newly founded improv group and I need to input it to fill the participant form. 

For that case, it would be seem approppriate to use input simillar to [this jQuery example](https://jqueryui.com/autocomplete/#categories), but consider case when user mistypes the team name. It seems like triviality, but I don't see a solution where we're in full control because we don't have the full list of possible options.

I don't want to burn too much time on this because it does not bring much value to the users.

**Comment by just-paja** [comment]
We've discussed this and decided to have it as a foreign key with single user value. There will be an extra endpoint listing all user typed values.
