### ISSUE TITLE
Think of different name for Order model

### ISSUE THREAD

**Issue by PetrDlouhy** [just-paja/improtresk-api#50]
Order is quite confusing, because it can mean sequence as well as order of workshop. It is also translated by Django as "pořadí". We need some more unambiguous name.

**Comment by just-paja** [comment]
@PetrDlouhy, do some google search, `Order` is a natural name for an instruction from a customer to buy. I vote for it to stay.

**Comment by PetrDlouhy** [comment]
I have `Order` associated with meanings `pořadí`, `příkaz` and `objednáva` is for me on the third place. It really confuses me even if I know it.

I suggest other name: `Application`, `Admission`, `YearAdmission`, `Entry` or `Registration`. The first one fits me the best.

**Comment by just-paja** [comment]
@PetrDlouhy, Order is a standard name for all eshops I've seen so far. Think of what name is best for any of our target user roles. Order just represents exactly what we need and is familiar to all users. I suggest you go on Amazon and order something now. Or just look it up on wiki.

https://en.wikipedia.org/wiki/Order_(business)

`Application` is not appropriate because that's another name for the program we are working on. Also it does not carry any information for any of our target user roles.
`Admission` and `YearAdmission` has nothing to do with order being paid.
`Entry` means nothing. Entry is item in list or the event of entering.
`Registration` is confusing because it is the process of user being registered. Has nothing to do with order being paid.
